### ISSUE TITLE
OMG, move this to a proper location

### ISSUE THREAD

**Issue by rxa254** [fincle/RoboTsar#1]
put this in our groups GitHub repo or else it gets lost when you leave oh noe aoksodkaokdoaksdkakskK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by awade** [comment]
alkdfjaslkfdjadslkfj

Ok

**Comment by awade** [comment]
Moved to CaltechExperimentalGravity ownership.  Also now deployed to nodus.
